CREATE TABLE IF NOT EXISTS transactions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    category TEXT NOT NULL,
    type category_type,
    accounts TEXT NOT NULL,
    amount NUMERIC(15, 2) NOT NULL,
    date_time TIMESTAMPTZ
)